services:
  - docker

install:
  - docker build -t minecraft-spongevanilla .
  - docker run -d -p 25565:25565 --name spongevanilla minecraft-spongevanilla

script:
  - sleep 10
  - docker ps | grep -q spongevanilla
